name: videogame_catalog
description: "A new Flutter project."
publish_to: "none"

version: 1.0.3+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  crypto: ^3.0.6
  video_player: ^2.10.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
